server:
  port: 8080

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    password: jenskohler
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: 'true'
        ddl-auto: create-drop
        show-sql: 'true'


#Postgres Config
#spring:
#  datasource:
#    username: root
#    url: jdbc:postgresql://localhost:5432/demo
#    password: jenskohler
#    initialize: true
#    initialization-mode: always
#  jpa.hibernate:
#    dialect: org.hibernate.dialect.PostgreSQLDialect
#    format_sql: 'true'
#    ddl-auto: create-drop
#    show-sql: 'true'

#server:
#  port: 8443
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:customer-service-keystore.p12
#    key-store-password: changeit
#    key-alias: customer-service
#    client-auth: want
#    trust-store: classpath:customer-service-truststore.p12
#    trust-store-password: changeit


feign:
  name: customer-feign
  url: http://localhost:18080
  #for mTLS use https://localhost:18443
