#MariaDB Config
spring:
  datasource:
    username: root
    url: jdbc:mysql://customer-service-mariadb:3306/demo?useSSL=false
    password: jenskohler
  jpa.hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    format_sql: 'true'
    ddl-auto: create-drop
    show-sql: 'true'

feign:
  name: feignCustomer
  url: http://order-service
  #for mTLS use https://localhost:18443

#Postgres Config
#spring:
#  datasource:
#    username: root
#    url: jdbc:postgresql://customer-service-postgresql:5432/demo
#    password: jenskohler
#    initialize: true
#    initialization-mode: always
#  jpa.hibernate:
#    dialect: org.hibernate.dialect.PostgreSQLDialect
#    format_sql: 'true'
#    ddl-auto: create-drop
#    show-sql: 'true'

