#MariaDB Config
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    password: jenskohler
  jpa.hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    format_sql: 'true'
    ddl-auto: create-drop
    show-sql: 'true'


#Postgres Config
#spring:
#  datasource:
#    username: root
#    url: jdbc:postgresql://localhost:5432/demo
#    password: jenskohler
#    initialize: true
#    initialization-mode: always
#  jpa.hibernate:
#    dialect: org.hibernate.dialect.PostgreSQLDialect
#    format_sql: 'true'
#    ddl-auto: create-drop
#    show-sql: 'true'

#server:
#  port: 18443
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:order-service-keystore.p12
#    key-store-password: changeit
#    key-alias: order-service
#    client-auth: need
#    trust-store: classpath:order-service-truststore.p12
#    trust-store-password: changeit